{
  "hash": "b07c37087396d219dab16da87d98cc76",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How well does education level predict the the time spent outdoors on work/school days among adults ages 20-59?\"\nauthor: \"Phuong Anh Lam (Anh Lam)\"\ndate: \"09-28-2026\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    date-format: iso\nexecute:\n  warning: false\n  message: false\n---\n\n# Setup and Data Ingest\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(janitor)\nlibrary(mice)\nlibrary(broom)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(naniar)\nlibrary(magrittr)\n\n# Download/read raw datasets\ndemo_raw <- read_xpt(\"data/P_DEMO.xpt\")\ndeq_raw  <- read_xpt(\"data/P_DEQ.xpt\")\n\n# Select relevant variables\ndemo <- demo_raw %>%\n  select(\n    SEQN, RIDSTATR, RIDAGEYR,\n    RIAGENDR, RIDRETH3, DMDEDUC2\n  )\n\ndeq <- deq_raw %>%\n  select(\n    SEQN, DED120, DED125, DEQ034D\n  )\n\n# Merge datasets\nsun_raw <- demo %>%\n  left_join(deq, by = \"SEQN\")\n\n# Restrict to adults ages 20-59 who completed the examination\nsun <- sun_raw %>%\n  filter(\n    RIDSTATR == 2,\n    RIDAGEYR >= 20,\n    RIDAGEYR <= 59\n  )\n```\n:::\n\n\n# **Cleaning the Data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mice)\n\n#Clean the data by replace any invalid responses (7,7777,9,9999,3333)\n\nsun_clean <- sun %>%\n  mutate(\n    DMDEDUC2 = replace(\n      DMDEDUC2,\n      DMDEDUC2 %in% c(7, 9),\n      NA\n    ),\n    \n    DEQ034D = replace(\n      DEQ034D,\n      DEQ034D %in% c(7, 9),\n      NA\n    ),\n    \n    DED120 = replace(\n      DED120,\n      DED120 %in% c(3333, 7777, 9999),\n      NA\n    ),\n    \n    DED125 = replace(\n      DED125,\n      DED125 %in% c(3333, 7777, 9999),\n      NA\n    )\n  )\n\n#Create useful categories\n\nsun_clean <- sun_clean %>%\n  mutate(\n    gender = factor(\n      RIAGENDR,\n      levels = c(1, 2),\n      labels = c(\"Male\", \"Female\")\n    ),\n    \n    race_ethnicity = factor(\n      RIDRETH3,\n      levels = c(1, 2, 3, 4, 6, 7),\n      labels = c(\n        \"Mexican American\",\n        \"Other Hispanic\",\n        \"Non-Hispanic White\",\n        \"Non-Hispanic Black\",\n        \"Non-Hispanic Asian\",\n        \"Other Race - Including Multi-Racial\"\n      )\n    ),\n    \n    education = case_when(\n      DMDEDUC2 %in% c(1, 2) ~ \"Less than high school\",\n      DMDEDUC2 == 3 ~ \"High school or GED\",\n      DMDEDUC2 == 4 ~ \"Some college or AA\",\n      DMDEDUC2 == 5 ~ \"College graduate or above\",\n      TRUE ~ NA_character_\n    ),\n    \n    education = factor(\n      education,\n      levels = c(\n        \"Less than high school\",\n        \"High school or GED\",\n        \"Some college or AA\",\n        \"College graduate or above\"\n      )\n    ),\n    \n    sunscreen = factor(\n      DEQ034D,\n      levels = c(1, 2, 3, 4, 5),\n      labels = c(\n        \"Always\",\n        \"Most of the time\",\n        \"Sometimes\",\n        \"Rarely\",\n        \"Never\"\n      )\n    ),\n    \n    regular_sunscreen = case_when(\n      DEQ034D %in% c(1, 2) ~ \"Regular\",\n      DEQ034D %in% c(3, 4, 5) ~ \"Not Regular\",\n      TRUE ~ NA_character_\n    ),\n    \n    regular_sunscreen = factor(\n      regular_sunscreen,\n      levels = c(\"Not Regular\", \"Regular\")\n    )\n  )\n\nsun_clean <- sun_clean %>%\n  rename(\n    outdoor_workday = DED120,\n    outdoor_nonworkday = DED125\n  )\n\nstudy2 <- sun_clean %>%\n  select(\n    SEQN,\n    outdoor_workday,\n    education,\n    RIDAGEYR,\n    gender,\n    race_ethnicity,\n    regular_sunscreen\n  )\n\n#Check dimension\ndim(study2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5403    7\n```\n\n\n:::\n\n```{.r .cell-code}\n#Summary and distinct variables check\nstudy2 %>%\n  summarize(\n    across(\n      everything(),\n      ~ sum(is.na(.))\n    )\n  ) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| SEQN| outdoor_workday| education| RIDAGEYR| gender| race_ethnicity| regular_sunscreen|\n|----:|---------------:|---------:|--------:|------:|--------------:|-----------------:|\n|    0|             535|         2|        0|      0|              0|                23|\n\n\n:::\n\n```{.r .cell-code}\nn_distinct(study2$outdoor_workday, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32\n```\n\n\n:::\n\n```{.r .cell-code}\nstudy2 <- study2 %>%\n  filter(\n    !is.na(outdoor_workday),\n    !is.na(education)\n  )\n\ndim(study2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4867    7\n```\n\n\n:::\n\n```{.r .cell-code}\nstudy2 %>%\n  summarize(\n    across(everything(), ~ sum(is.na(.)))\n  ) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| SEQN| outdoor_workday| education| RIDAGEYR| gender| race_ethnicity| regular_sunscreen|\n|----:|---------------:|---------:|--------:|------:|--------------:|-----------------:|\n|    0|               0|         0|        0|      0|              0|                17|\n\n\n:::\n\n```{.r .cell-code}\nstudy2_clean <- mice(\n  study2,\n  m = 1,\n  maxit = 5,\n  seed = 431,\n  printFlag = FALSE\n)\n\nstudy2_final <- complete(study2_clean)\n\ndim(study2_final)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4867    7\n```\n\n\n:::\n\n```{.r .cell-code}\nstudy2_final %>%\n  summarize(\n    across(everything(), ~ sum(is.na(.)))\n  ) %>%\n  pivot_longer(\n    everything(),\n    names_to = \"Variable\",\n    values_to = \"Number Missing\"\n  ) %>%\n  kable(\n    caption = \"Missing Values After Data Cleaning\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Missing Values After Data Cleaning\n\n|Variable          | Number Missing|\n|:-----------------|--------------:|\n|SEQN              |              0|\n|outdoor_workday   |              0|\n|education         |              0|\n|RIDAGEYR          |              0|\n|gender            |              0|\n|race_ethnicity    |              0|\n|regular_sunscreen |              0|\n\n\n:::\n:::\n\n\n# Codebook and Data Description\n\n## Codebook\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncodebook <- tibble(\n  Variable = c(\n    \"SEQN\",\n    \"outdoor_workday\",\n    \"education\",\n    \"RIDAGEYR\",\n    \"gender\",\n    \"race_ethnicity\",\n    \"regular_sunscreen\"\n  ),\n  Description = c(\n    \"Participant ID\",\n    \"Time spent outdoors on work/school days (minutes)\",\n    \"Highest education level\",\n    \"Age in years\",\n    \"Gender\",\n    \"Race/ethnicity\",\n    \"Regular sunscreen use\"\n  ),\n  Role = c(\n    \"ID\",\n    \"Outcome\",\n    \"Key predictor\",\n    \"Predictor\",\n    \"Predictor\",\n    \"Predictor\",\n    \"Predictor\"\n  )\n)\n\ncodebook %>%\n  kable(\n    caption = \"Codebook for Study 2 Analytic Variables\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Codebook for Study 2 Analytic Variables\n\n|Variable          |Description                                       |Role          |\n|:-----------------|:-------------------------------------------------|:-------------|\n|SEQN              |Participant ID                                    |ID            |\n|outdoor_workday   |Time spent outdoors on work/school days (minutes) |Outcome       |\n|education         |Highest education level                           |Key predictor |\n|RIDAGEYR          |Age in years                                      |Predictor     |\n|gender            |Gender                                            |Predictor     |\n|race_ethnicity    |Race/ethnicity                                    |Predictor     |\n|regular_sunscreen |Regular sunscreen use                             |Predictor     |\n\n\n:::\n:::\n\n\n## Analytic Tibble\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Tibble\nstudy2_final %>%\n  slice_head(n = 10) %>%\n  kable(\n    caption = \"First 10 Observations of the Study 2 Analytic Dataset\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: First 10 Observations of the Study 2 Analytic Dataset\n\n|   SEQN| outdoor_workday|education                 | RIDAGEYR|gender |race_ethnicity     |regular_sunscreen |\n|------:|---------------:|:-------------------------|--------:|:------|:------------------|:-----------------|\n| 109266|              30|College graduate or above |       29|Female |Non-Hispanic Asian |Not Regular       |\n| 109273|             360|Some college or AA        |       36|Male   |Non-Hispanic White |Not Regular       |\n| 109284|             240|Less than high school     |       44|Female |Mexican American   |Regular           |\n| 109286|              60|College graduate or above |       33|Female |Non-Hispanic Asian |Regular           |\n| 109291|             120|College graduate or above |       42|Female |Non-Hispanic Asian |Not Regular       |\n| 109292|               0|High school or GED        |       58|Male   |Other Hispanic     |Not Regular       |\n| 109293|             120|High school or GED        |       44|Male   |Non-Hispanic White |Not Regular       |\n| 109295|               0|Less than high school     |       54|Female |Mexican American   |Not Regular       |\n| 109297|               0|Some college or AA        |       30|Female |Non-Hispanic Asian |Not Regular       |\n| 109300|              30|College graduate or above |       54|Female |Non-Hispanic Asian |Not Regular       |\n\n\n:::\n:::\n\n\n## Numeric Description\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Data summary\nnumeric_summary <- tibble(\n  Variable = c(\"Outdoor time (minutes)\", \"Age (years)\"),\n  Mean = c(\n    mean(study2_final$outdoor_workday),\n    mean(study2_final$RIDAGEYR)\n  ),\n  SD = c(\n    sd(study2_final$outdoor_workday),\n    sd(study2_final$RIDAGEYR)\n  ),\n  Median = c(\n    median(study2_final$outdoor_workday),\n    median(study2_final$RIDAGEYR)\n  ),\n  Min = c(\n    min(study2_final$outdoor_workday),\n    min(study2_final$RIDAGEYR)\n  ),\n  Max = c(\n    max(study2_final$outdoor_workday),\n    max(study2_final$RIDAGEYR)\n  )\n)\n\nnumeric_summary %>%\n  kable(\n    digits = 1,\n    caption = \"Summary of Numeric Variables\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of Numeric Variables\n\n|Variable               |  Mean|    SD| Median| Min| Max|\n|:----------------------|-----:|-----:|------:|---:|---:|\n|Outdoor time (minutes) | 117.5| 139.8|     60|   0| 480|\n|Age (years)            |  39.6|  11.5|     40|  20|  59|\n\n\n:::\n:::\n\n\n# My Research Question\n\n**How well does education level predict time spent outdoors on work/school days among adults ages 20–59 after accounting for age, gender, race/ethnicity, and regular sunscreen use?**\n\nKey predictor will be *education*. The quantitative outcome would be *outdoor_workday* (time spent outdoors on work/school days). Additional predictors are *age*, *gender*, *race/ ethnicity*, and *regular_sunscreen* (regular sunscreen use).\n\n# Partitioning the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Partition the data (train and test)\nset.seed(431)\n\nstudy2_train <- study2_final %>%\n  slice_sample(prop = 0.70)\n\nstudy2_test <- study2_final %>%\n  anti_join(study2_train, by = \"SEQN\")\n\n#Check size for 70/30\nnrow(study2_train)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3406\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(study2_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1461\n```\n\n\n:::\n\n```{.r .cell-code}\n#Verify that no one is in both training and test sets at the same time\npartition_check <- tibble(\n  Dataset = c(\"Full analytic sample\", \"Training\", \"Test\"),\n  n = c(\n    nrow(study2_final),\n    nrow(study2_train),\n    nrow(study2_test)\n  )\n)\n\npartition_check %>%\n  kable(\n    caption = \"Study 2 Training and Test Sample Sizes\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Study 2 Training and Test Sample Sizes\n\n|Dataset              |    n|\n|:--------------------|----:|\n|Full analytic sample | 4867|\n|Training             | 3406|\n|Test                 | 1461|\n\n\n:::\n\n```{.r .cell-code}\n# Check that no participant appears in both datasets\nintersect(\n  study2_train$SEQN,\n  study2_test$SEQN\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnumeric(0)\n```\n\n\n:::\n:::\n\n\n# Transforming the Outcome\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Plot\nggplot(study2_train, aes(x = outdoor_workday)) +\n  geom_histogram(bins = 30) +\n  labs(\n    title = \"Distribution of Outdoor Time in Training Data\",\n    x = \"Time spent outdoors on work/school days (minutes)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Study2_draft_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Summary\nstudy2_train %>%\n  summarize(\n    mean = mean(outdoor_workday),\n    sd = sd(outdoor_workday),\n    median = median(outdoor_workday),\n    min = min(outdoor_workday),\n    max = max(outdoor_workday)\n  ) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|  mean|    sd| median| min| max|\n|-----:|-----:|------:|---:|---:|\n| 115.7| 138.1|     60|   0| 480|\n\n\n:::\n\n```{.r .cell-code}\n#Log transformation is used because the data is skewed to the right, so linear transformation would not work. The log calculations will compress the big datapoints while the effect is minimal on small datapoints, so overall it should somewhat account for the dramatic skew. \n\n#Log transformation\nstudy2_train <- study2_train %>%\n  mutate(\n    log_outdoor_workday = log(outdoor_workday + 1)\n  )\n\nstudy2_test <- study2_test %>%\n  mutate(\n    log_outdoor_workday = log(outdoor_workday + 1)\n  )\n\n#Plot the log distribution\n\nggplot(study2_train, aes(x = log_outdoor_workday)) +\n  geom_histogram(bins = 30) +\n  labs(\n    title = \"Distribution of Log-Transformed Outdoor Time\",\n    x = \"log(Outdoor time + 1)\",\n    y = \"Count\"\n  ) \n```\n\n::: {.cell-output-display}\n![](Study2_draft_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#This log calculation produces a large portion for 0 since log (0+1) = 0 for people that reported outdoor_workday = 0. Otherwise, the distribution for other time interval looks better, though the distribution is still not normal. The improvement is a sign to proceed with the model fitting.\n```\n:::\n\n\n# The Big Model \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#The Big Model uses log transformation to predict the outdoor time on work/school days as the the outcome, including additional predictors such as education, age, gender, race/ethnicity, and regular sunscreen use. \n\n#Big Model\nbig_model <- lm(\n  log_outdoor_workday ~ education + RIDAGEYR + gender +\n    race_ethnicity + regular_sunscreen,\n  data = study2_train\n)\n\n# Coefficient summary\ntidy(big_model, conf.int = TRUE) %>%\n  kable(\n    digits = 3,\n    caption = \"Coefficient Estimates for the Big Model\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Coefficient Estimates for the Big Model\n\n|term                                              | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------------------------------------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)                                       |    4.849|     0.165|    29.351|   0.000|    4.525|     5.173|\n|educationHigh school or GED                       |   -0.075|     0.115|    -0.651|   0.515|   -0.300|     0.150|\n|educationSome college or AA                       |   -0.178|     0.110|    -1.620|   0.105|   -0.394|     0.037|\n|educationCollege graduate or above                |   -0.574|     0.117|    -4.920|   0.000|   -0.802|    -0.345|\n|RIDAGEYR                                          |   -0.017|     0.003|    -5.644|   0.000|   -0.022|    -0.011|\n|genderFemale                                      |   -0.980|     0.069|   -14.160|   0.000|   -1.116|    -0.845|\n|race_ethnicityOther Hispanic                      |    0.061|     0.140|     0.438|   0.661|   -0.213|     0.336|\n|race_ethnicityNon-Hispanic White                  |    0.260|     0.115|     2.268|   0.023|    0.035|     0.485|\n|race_ethnicityNon-Hispanic Black                  |    0.296|     0.117|     2.536|   0.011|    0.067|     0.525|\n|race_ethnicityNon-Hispanic Asian                  |   -0.368|     0.135|    -2.733|   0.006|   -0.632|    -0.104|\n|race_ethnicityOther Race - Including Multi-Racial |    0.401|     0.172|     2.325|   0.020|    0.063|     0.739|\n|regular_sunscreenRegular                          |   -0.114|     0.090|    -1.270|   0.204|   -0.290|     0.062|\n\n\n:::\n:::\n\n\n# The Small Model \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Small Model uses the same log transformation to calculate the outdoor time on work/school days as the outcome, but it only uses education as the key predictor. \n\n#Small Model\nsmall_model <- lm(\n  log_outdoor_workday ~ education,\n  data = study2_train\n)\n\n# Coefficient summary\ntidy(small_model, conf.int = TRUE) %>%\n  kable(\n    digits = 3,\n    caption = \"Coefficient Estimates for the Smaller Model\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Coefficient Estimates for the Smaller Model\n\n|term                               | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:----------------------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)                        |    3.791|     0.092|    41.236|   0.000|    3.611|     3.971|\n|educationHigh school or GED        |    0.060|     0.117|     0.518|   0.605|   -0.168|     0.289|\n|educationSome college or AA        |   -0.147|     0.110|    -1.341|   0.180|   -0.362|     0.068|\n|educationCollege graduate or above |   -0.698|     0.113|    -6.168|   0.000|   -0.920|    -0.476|\n\n\n:::\n:::\n\n\n# In-Sample Comparison\n\n## Quality of Fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Evaluation/Comparision of the two models using R squared, AIC, and BIC\n\n\nbig_fit <- glance(big_model) %>%\n  select(r.squared, adj.r.squared, AIC, BIC) %>%\n  mutate(Model = \"Big Model\")\n\nsmall_fit <- glance(small_model) %>%\n  select(r.squared, adj.r.squared, AIC, BIC) %>%\n  mutate(Model = \"Smaller Model\")\n\nbind_rows(big_fit, small_fit) %>%\n  select(Model, everything()) %>%\n  kable(\n    digits = 3,\n    caption = \"In-Sample Model Fit Comparison\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: In-Sample Model Fit Comparison\n\n|Model         | r.squared| adj.r.squared|      AIC|      BIC|\n|:-------------|---------:|-------------:|--------:|--------:|\n|Big Model     |     0.101|         0.098| 14254.58| 14334.32|\n|Smaller Model |     0.022|         0.021| 14525.42| 14556.08|\n\n\n:::\n:::\n\n\nThe R squared value is higher for the Big model, indicating that the model has a better fit compared to the Small model, though it only accounts for about 10% of the variation. Nonetheles, the AIC and BIC results for the Big model are smaller. Overall, so far, the Big model seems to be a stronger model.\n\n## Assessing Assumptions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check Regression Assumptions using Residual and Normal Q-Q plots for the Big model and Small model \n\n#Big Model\nbig_aug <- augment(big_model)\n\n# Residuals vs Fitted\nggplot(big_aug, aes(x = .fitted, y = .resid)) +\n  geom_point() +\n  geom_smooth(\n    method = \"lm\",\n    se = FALSE\n  ) +\n  labs(\n    title = \"Big Model: Residuals vs Fitted\",\n    x = \"Fitted values\",\n    y = \"Residuals\"\n  )\n```\n\n::: {.cell-output-display}\n![](Study2_draft_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Normal Q-Q plot\nggplot(big_aug, aes(sample = .resid)) +\n  stat_qq() +\n  stat_qq_line() +\n  labs(\n    title = \"Big Model: Normal Q-Q\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  )\n```\n\n::: {.cell-output-display}\n![](Study2_draft_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#Small Model\nsmall_aug <- augment(small_model)\n\n# Residuals vs Fitted\nggplot(small_aug, aes(x = .fitted, y = .resid)) +\n  geom_point() +\n  geom_smooth(\n    method = \"loess\",\n    se = FALSE\n  ) +\n  labs(\n    title = \"Small Model: Residuals vs Fitted\",\n    x = \"Fitted values\",\n    y = \"Residuals\"\n  )\n```\n\n::: {.cell-output-display}\n![](Study2_draft_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# Normal Q-Q plot\nggplot(small_aug, aes(sample = .resid)) +\n  stat_qq() +\n  stat_qq_line() +\n  labs(\n    title = \"Small Model: Normal Q-Q\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  )\n```\n\n::: {.cell-output-display}\n![](Study2_draft_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n:::\n\n\n## Comparing the Model\n\nThe results are very different for the Big model and the Small model.\n\nThe Big Model has higher R squared and adjusted R squared values, which means that it explains more of the variation in the outdoor time in the training data.\n\nIt's very interesting how the Residuals for the Big model are somewhat in a diagonal position, and it does not agree with the fitted values. The values starting at around -2 seem somewhat out of the normal range. The Residuals for the Small model have substainable spread and do not align well with the fitted line. The regression residuals only partially follow the normal distribution, as showed in the Normal Q-Q plot in the Big model. The same observation can be made with the Small model: Normal Q-Q plot. While these results are not ideal, we should still proceed with the predictions to see if we could get a different result.\n\n# Model Validation\n\n## Calculating Prediction Errors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Big Model predictions on test data\nbig_test <- study2_test %>%\n  mutate(\n    predicted_log = predict(big_model, newdata = study2_test),\n    predicted_minutes = exp(predicted_log) - 1,\n    prediction_error = outdoor_workday - predicted_minutes\n  )\n\n# Small Model predictions on original scale\nsmall_test <- study2_test %>%\n  mutate(\n    predicted_log = predict(small_model, newdata = study2_test),\n    predicted_minutes = exp(predicted_log) - 1,\n    prediction_error = outdoor_workday - predicted_minutes\n  )\n```\n:::\n\n\n## Visualizing the Predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Actual vs Predicted Plot\n\nprediction_plot <- bind_rows(\n  big_test %>%\n    select(outdoor_workday, predicted_minutes) %>%\n    mutate(Model = \"Big Model\"),\n  \n  small_test %>%\n    select(outdoor_workday, predicted_minutes) %>%\n    mutate(Model = \"Small Model\")\n)\n\nggplot(\n  prediction_plot,\n  aes(x = outdoor_workday, y = predicted_minutes)\n) +\n  geom_point(alpha = 0.4) +\n  geom_abline(\n    intercept = 0,\n    slope = 1,\n    linetype = \"dashed\"\n  ) +\n  facet_wrap(~ Model) +\n  labs(\n    title = \"Actual vs. Predicted Outdoor Time\",\n    x = \"Actual outdoor time (minutes)\",\n    y = \"Predicted outdoor time (minutes)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Study2_draft_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n## Summarizing the Errors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Big Model test performance\nbig_validation <- big_test %>%\n  summarize(\n    RMSPE = sqrt(mean(prediction_error^2)),\n    MAPE = mean(abs(prediction_error)),\n    MAE = max(abs(prediction_error)),\n    validated_R2 = cor(outdoor_workday, predicted_minutes)^2\n  )\n\n# Small Model test performance\nsmall_validation <- small_test %>%\n  summarize(\n    RMSPE = sqrt(mean(prediction_error^2)),\n    MAPE = mean(abs(prediction_error)),\n    MAE = max(abs(prediction_error)),\n    validated_R2 = cor(outdoor_workday, predicted_minutes)^2\n  )\n\n#Clean table\nbind_rows(\n  Big_Model = big_validation,\n  Small_Model = small_validation,\n  .id = \"Model\"\n) %>%\n  \n  kable(\n    digits = 3,\n    caption = \"Model Performance on the Test Data\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Model Performance on the Test Data\n\n|Model       |   RMSPE|    MAPE|     MAE| validated_R2|\n|:-----------|-------:|-------:|-------:|------------:|\n|Big_Model   | 157.152| 100.461| 466.855|        0.138|\n|Small_Model | 165.532| 104.731| 458.968|        0.046|\n\n\n:::\n:::\n\n\n## Comparing the Models\n\nThe Big Model has a lower RMSPE (157 minutes) and MAE (100 minutes) compared to the Small Model (165 and 104 minutes, respectively). The Big Model also has a higher R square value (0.138 vs 0.046), which means its predictions are closer to the actual outdoor time values. Overall, the Big Model shows better predictive performance, though the prediction errors are still significant in both models.\n\n# Discussion\n\n## Chosen Model\n\nI choose the Big Model because it shows better results on almost all of the validation tests, including higher R squared values, low AIC and BIC values, than the Small Model. In addition, its prediction errors (RMSPE and MAE) are also smaller than those for the Small Model. However, it still has significant limitations since the error values are relatively large.\n\n## Answering My Question\n\nWhile *education* as a predictor alone is proven inefficient to predict the *outdoor time* on work/school days, adding multiple predictors seem to only improve the outcome to a certain extent. We can see that the predicted outdoor time has much variations with the Big Model.\n\nLooking at the coefficient tables of the Big Model, *education* is related to *outdoor time* mainly for college graduates. Participants with high school and some college education do not have a statistically significant difference in otudoor time compared to those with less than high school education. However, college graduates and above tend to spend less time outdoors than those with less than a high school education. This is a significant difference (p\\<0.001), taking into account for *age, gender, race, and regular sunscreen use*.\n\n## Next Steps\n\nI think the next steps should be looking at other predictors such as occupation or work schedule. In addition, other regression models could be explored since the log transformation did not fully account for the large prediction errors at the end.\n\n## Reflection\n\nIt's important to evaluate a model using both the training and testing data. We see that even though the Big Model surpasses the Small Model on most measurements (R squared, AIC, BIC results, etc.), the plots tell us that the improved performance of the Big Model still has significant variations from the actual values. Thus, adding more predictors might actually have complicated the performance of the model, even after showing some initial potential.\n\n## Final Section\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxfun::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.6.2\n\nLocale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8\n\nPackage version:\n  askpass_1.2.1       backports_1.5.1     base64enc_0.1.6    \n  bit_4.6.0           bit64_4.8.6         blob_1.3.0         \n  boot_1.3-32         broom_1.0.13        bslib_0.12.0       \n  cachem_1.1.0        callr_3.8.0         cellranger_1.1.0   \n  cli_3.6.6           clipr_0.8.1         codetools_0.2-20   \n  compiler_4.6.1      conflicted_1.2.0    cpp11_0.5.5        \n  crayon_1.5.3        curl_8.0.0          data.table_1.18.6.1\n  DBI_1.3.0           dbplyr_2.6.0        digest_0.6.39      \n  dplyr_1.2.1         dtplyr_1.3.3        evaluate_1.0.5     \n  farver_2.1.2        fastmap_1.2.0       fontawesome_0.5.3  \n  forcats_1.0.1       foreach_1.5.2       fs_2.1.0           \n  gargle_1.6.1        generics_0.1.4      ggplot2_4.0.3      \n  glmnet_5.1          glue_1.8.1          googledrive_2.1.2  \n  googlesheets4_1.1.2 graphics_4.6.1      grDevices_4.6.1    \n  grid_4.6.1          gridExtra_2.3.1     gtable_0.3.6       \n  haven_2.5.5         highr_0.12          hms_1.1.4          \n  htmltools_0.5.9     htmlwidgets_1.6.4   httr_1.4.8         \n  ids_1.0.1           isoband_0.3.0       iterators_1.0.14   \n  janitor_2.2.1       jomo_2.7-6          jquerylib_0.1.4    \n  jsonlite_2.0.0      knitr_1.52          labeling_0.4.3     \n  lattice_0.22-9      lifecycle_1.0.5     lme4_2.0-6         \n  lubridate_1.9.5     magrittr_2.0.5      MASS_7.3-65        \n  Matrix_1.7-5        memoise_2.0.1       methods_4.6.1      \n  mgcv_1.9-4          mice_3.19.0         mime_0.13          \n  minqa_1.2.8         mitml_0.4-5         modelr_0.1.11      \n  naniar_1.1.0        nlme_3.1-169        nloptr_2.2.1       \n  nnet_7.3-20         norm_1.0.11.1       numDeriv_2016.8.1.1\n  openssl_2.4.2       ordinal_2026.7.26   otel_0.2.0         \n  pan_2.0             parallel_4.6.1      patchwork_1.3.2    \n  pillar_1.11.1       pkgconfig_2.0.3     plyr_1.8.9         \n  prettyunits_1.2.0   processx_3.9.0      progress_1.2.3     \n  ps_1.9.3            purrr_1.2.2         R6_2.6.1           \n  ragg_1.5.2          rappdirs_0.3.4      rbibutils_2.4.1    \n  RColorBrewer_1.1-3  Rcpp_1.1.2          RcppEigen_0.3.4.0.2\n  Rdpack_2.6.6        readr_2.2.0         readxl_1.5.0       \n  reformulas_0.4.4    rematch_2.0.0       rematch2_2.1.2     \n  reprex_2.1.1        rlang_1.3.0         rmarkdown_2.31     \n  rpart_4.1.27        rstudioapi_0.19.0   rvest_1.0.5        \n  S7_0.2.2            sass_0.4.10         scales_1.4.0       \n  selectr_0.6.0       shape_1.4.6.1       snakecase_0.11.1   \n  splines_4.6.1       stats_4.6.1         stats4_4.6.1       \n  stringi_1.8.9       stringr_1.6.0       survival_3.8-6     \n  sys_3.4.3           systemfonts_1.3.2   textshaping_1.0.5  \n  tibble_3.3.1        tidyr_1.3.2         tidyselect_1.2.1   \n  tidyverse_2.0.0     timechange_0.4.0    tinytex_0.60       \n  tools_4.6.1         tzdb_0.5.0          ucminf_1.2.3       \n  UpSetR_1.4.1        utf8_1.2.6          utils_4.6.1        \n  uuid_1.2.2          vctrs_0.7.3         viridis_0.6.5      \n  viridisLite_0.4.3   visdat_0.6.1        vroom_1.7.1        \n  withr_3.0.3         xfun_0.61           xml2_1.6.0         \n  yaml_2.3.12        \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Study2_draft_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}