{
  "hash": "728fb59922d79d4032a64d9d287456fb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sun Exposure and Sun Protection Behaviors In Adults Ages 20-59\"\nauthor: \"Phuong Anh Lam (Anh Lam)\"\ndate: \"09-27-2026\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    date-format: iso\nexecute:\n  warning: false\n  message: false\n---\n\n# **Setup and Data Ingest**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Install necessary packages\n\nknitr::opts_chunk$set(comment = NA)\n#install.packages(c(\"tidyverse\",\"janitor\",\"knitr\",\"magrittr\",\"broom\",\"naniar\",\"patchwork\"))\n#install.packages(\"haven\")\n#install.packages(\"nhanesA\")\nlibrary(nhanesA)\nlibrary(haven)\nlibrary(janitor)\nlibrary(knitr) \nlibrary(magrittr)\nlibrary(broom) \nlibrary(naniar)\nlibrary(patchwork)\nlibrary(tidyverse)\n\n\n#Download raw datasets from P_DEMO, P_DEQ, and P_OCQ\n\n#getwd()\n#file.exists(\"data/P_DEMO.xpt\")\ndemo_raw <- read_xpt(\"data/P_DEMO.xpt\")\ndeq_raw <- read_xpt(\"data/P_DEQ.xpt\")\nocq_raw <- read_xpt(\"data/P_OCQ.xpt\")\n\n#Select relevant variables in datasets\ndemo <- demo_raw %>%\n  select(SEQN, RIDSTATR, RIDAGEYR, RIAGENDR, RIDRETH3, DMDEDUC2)\n\ndeq <- deq_raw %>%\n  select(SEQN,DED120, DED125, DEQ034D)\n\n#Merge and define necessary data\nsun_raw <- demo %>%\n  left_join(deq, by = \"SEQN\")\n\nsun <- sun_raw %>%\n  filter(\n    RIDSTATR == 2,\n    RIDAGEYR >= 20,\n    RIDAGEYR <= 59\n  )\n```\n:::\n\n\n# **Cleaning the Data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data Cleaning.\n\n#Deduct anything that corresponds to Refused to answer (7 or 7777), Don't know (9 or 9999), and Does not work for DED120 (3333)\n\nsun_clean <- sun %>%\n  mutate(\n    DMDEDUC2 = replace(\n      DMDEDUC2,\n      DMDEDUC2 %in% c(7, 9),\n      NA\n    ),\n    \n    DEQ034D = replace(\n      DEQ034D,\n      DEQ034D %in% c(7, 9),\n      NA\n    ),\n    \n    DED120 = replace(\n      DED120,\n      DED120 %in% c(3333, 7777, 9999),\n      NA\n    ),\n    \n    DED125 = replace(\n      DED125,\n      DED125 %in% c(3333, 7777, 9999),\n      NA\n    )\n  )\n\n#Create useful categories\n\nsun_clean <- sun_clean %>%\n  mutate(\n    gender = factor(\n      RIAGENDR,\n      levels = c(1, 2),\n      labels = c(\"Male\", \"Female\")\n    ),\n    \n    race_ethnicity = factor(\n      RIDRETH3,\n      levels = c(1, 2, 3, 4, 6, 7),\n      labels = c(\n        \"Mexican American\",\n        \"Other Hispanic\",\n        \"Non-Hispanic White\",\n        \"Non-Hispanic Black\",\n        \"Non-Hispanic Asian\",\n        \"Other Race - Including Multi-Racial\"\n      )\n    ),\n    \n    education = case_when(\n      DMDEDUC2 %in% c(1, 2) ~ \"Less than high school\",\n      DMDEDUC2 == 3 ~ \"High school or GED\",\n      DMDEDUC2 == 4 ~ \"Some college or AA\",\n      DMDEDUC2 == 5 ~ \"College graduate or above\",\n      TRUE ~ NA_character_\n    ),\n    \n    education = factor(\n      education,\n      levels = c(\n        \"Less than high school\",\n        \"High school or GED\",\n        \"Some college or AA\",\n        \"College graduate or above\"\n      )\n    ),\n    \n    sunscreen = factor(\n      DEQ034D,\n      levels = c(1, 2, 3, 4, 5),\n      labels = c(\n        \"Always\",\n        \"Most of the time\",\n        \"Sometimes\",\n        \"Rarely\",\n        \"Never\"\n      )\n    ),\n    \n    regular_sunscreen = case_when(\n      DEQ034D %in% c(1, 2) ~ \"Regular\",\n      DEQ034D %in% c(3, 4, 5) ~ \"Not Regular\",\n      TRUE ~ NA_character_\n    ),\n    \n    regular_sunscreen = factor(\n      regular_sunscreen,\n      levels = c(\"Not Regular\", \"Regular\")\n    )\n  )\n\nsun_clean <- sun_clean %>%\n  rename(\n    outdoor_workday = DED120,\n    outdoor_nonworkday = DED125\n  )\n\n#Study 1 Final Tibble\n\n#Assign only necessary catorgories to Study1 dataset, drop NA data and any unused categories\n\nstudy1 <- sun_clean %>%\n  select(\n    SEQN,\n    RIDSTATR,\n    RIDAGEYR,\n    outdoor_workday,\n    outdoor_nonworkday,\n    gender,\n    education,\n    sunscreen,\n    regular_sunscreen\n  ) %>%\n  drop_na() %>%\n  droplevels()\n```\n:::\n\n\n# **Codebook and Data Description**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Code book\n\ncodebook <- tibble(\n  Variable = c(\n    \"SEQN\",\n    \"outdoor_workday\",\n    \"outdoor_nonworkday\",\n    \"gender\",\n    \"education\",\n    \"sunscreen\",\n    \"regular_sunscreen\"\n  ),\n  \n  Description = c(\n    \"NHANES participant identifier\",\n    \"Minutes outdoors from 9am to 5pm on work or school days\",\n    \"Minutes outdoors from 9am to 5pm on nonwork or nonschool days\",\n    \"Gender\",\n    \"Education/degree status\",\n    \"Frequency of sunscreen use when outside on a very sunny day for more than 1hour\",\n    \"Regular sunscreen use, from always, most of the time to rarely and never\"\n  ),\n  \n  Type = c(\n    \"Identifier\",\n    \"Quant\",\n    \"Quant\",\n    \"Binary\",\n    \"Cat\",\n    \"Cat\",\n    \"Binary\"\n    \n  ),\n  \n  'Original Variable' = c(\n    \"SEQN\",\n    \"DED120\",\n    \"DED125\",\n    \"RIAGENDR\",\n    \"DMDEDUC2\",\n    \"DEQ034D\",\n    \"DEQ034D\"\n    \n  )\n)\n  \ncodebook %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Variable           |Description                                                                     |Type       |Original Variable |\n|:------------------|:-------------------------------------------------------------------------------|:----------|:-----------------|\n|SEQN               |NHANES participant identifier                                                   |Identifier |SEQN              |\n|outdoor_workday    |Minutes outdoors from 9am to 5pm on work or school days                         |Quant      |DED120            |\n|outdoor_nonworkday |Minutes outdoors from 9am to 5pm on nonwork or nonschool days                   |Quant      |DED125            |\n|gender             |Gender                                                                          |Binary     |RIAGENDR          |\n|education          |Education/degree status                                                         |Cat        |DMDEDUC2          |\n|sunscreen          |Frequency of sunscreen use when outside on a very sunny day for more than 1hour |Cat        |DEQ034D           |\n|regular_sunscreen  |Regular sunscreen use, from always, most of the time to rarely and never        |Binary     |DEQ034D           |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Analysis Table\nstudy1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,821 × 9\n     SEQN RIDSTATR RIDAGEYR outdoor_workday outdoor_nonworkday gender education \n    <dbl>    <dbl>    <dbl>           <dbl>              <dbl> <fct>  <fct>     \n 1 109266        2       29              30                 60 Female College g…\n 2 109273        2       36             360                240 Male   Some coll…\n 3 109284        2       44             240                300 Female Less than…\n 4 109286        2       33              60                120 Female College g…\n 5 109291        2       42             120                  0 Female College g…\n 6 109292        2       58               0                  0 Male   High scho…\n 7 109293        2       44             120                240 Male   High scho…\n 8 109295        2       54               0                 60 Female Less than…\n 9 109297        2       30               0                120 Female Some coll…\n10 109300        2       54              30                 30 Female College g…\n# ℹ 4,811 more rows\n# ℹ 2 more variables: sunscreen <fct>, regular_sunscreen <fct>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Data Summary\nstudy1 %>%\n  summarize(\n    n = n(),\n      age_mean = mean(RIDAGEYR),\n      age_sd = sd(RIDAGEYR),\n      age_min = min(RIDAGEYR),\n      age_max = max(RIDAGEYR),\n      workday_mean = mean(outdoor_workday),\n      workday_sd = sd(outdoor_workday),\n      workday_median = median(outdoor_workday),\n      workday_min = min(outdoor_workday),\n      workday_max = max(outdoor_workday),\n      nonworkday_mean = mean(outdoor_nonworkday),\n      nonworkday_sd = sd(outdoor_nonworkday),\n      nonworkday_median = median(outdoor_nonworkday),\n      nonworkday_min = min(outdoor_nonworkday),\n      nonworkday_max = max(outdoor_nonworkday)\n  ) %>%\n  \n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|    n| age_mean| age_sd| age_min| age_max| workday_mean| workday_sd| workday_median| workday_min| workday_max| nonworkday_mean| nonworkday_sd| nonworkday_median| nonworkday_min| nonworkday_max|\n|----:|--------:|------:|-------:|-------:|------------:|----------:|--------------:|-----------:|-----------:|---------------:|-------------:|-----------------:|--------------:|--------------:|\n| 4821|     39.6|   11.5|      20|      59|        117.5|      139.7|             60|           0|         480|           151.1|         126.8|               120|              0|            480|\n\n\n:::\n\n```{.r .cell-code}\n#Turn data into percentages for easy intepretation  \nstudy1 %>%\n  tabyl(gender) %>%\n  adorn_pct_formatting(digits = 1) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|gender |    n|percent |\n|:------|----:|:-------|\n|Male   | 2346|48.7%   |\n|Female | 2475|51.3%   |\n\n\n:::\n\n```{.r .cell-code}\nstudy1 %>%\n  tabyl(education) %>%\n  adorn_pct_formatting(digits = 1) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|education                 |    n|percent |\n|:-------------------------|----:|:-------|\n|Less than high school     |  738|15.3%   |\n|High school or GED        | 1098|22.8%   |\n|Some college or AA        | 1671|34.7%   |\n|College graduate or above | 1314|27.3%   |\n\n\n:::\n\n```{.r .cell-code}\nstudy1 %>%\n  tabyl(sunscreen) %>%\n  adorn_pct_formatting(digits = 1) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|sunscreen        |    n|percent |\n|:----------------|----:|:-------|\n|Always           |  394|8.2%    |\n|Most of the time |  590|12.2%   |\n|Sometimes        | 1022|21.2%   |\n|Rarely           |  903|18.7%   |\n|Never            | 1912|39.7%   |\n\n\n:::\n\n```{.r .cell-code}\nstudy1 %>%\n  tabyl(regular_sunscreen) %>%\n  adorn_pct_formatting(digits = 1) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|regular_sunscreen |    n|percent |\n|:-----------------|----:|:-------|\n|Not Regular       | 3837|79.6%   |\n|Regular           |  984|20.4%   |\n\n\n:::\n\n```{.r .cell-code}\nstudy1 %>%\n  tabyl(RIDSTATR) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| RIDSTATR|    n| percent|\n|--------:|----:|-------:|\n|        2| 4821|       1|\n\n\n:::\n:::\n\n\n# **Data Analysis A**\n\n## The Question\n\n**What does time spent outdoors between 9am and 5pm looks like on work or school days versus on non-work/ non-school days for adult ages 20-59?**\n\nThis can be done by comparing the means of the time spend by the two groups. But two plots side-by-side woud better demonstrate how the time spent differs at each time interval.\n\n## Describing The Data \n\nThe variables we're looking at are outdoor_workday and outdoor_nonworkday, which correspond to the time spent outdoors on work/ school days and the the time spent outdoors on nonwork/ school days. We want to see whether or not people spend more time outdoors when they don't have school or work responsibilities.\n\n## Main Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Main Analysis: Histogram plots for time spent outdoors for the two groups.\n\n#Plots\np1 <- ggplot(study1, aes(x = outdoor_workday)) +\n  geom_histogram(bins = 30) +\n  labs(\n    title = \"Work/School Days\",\n    x = \"Time spent outdoors (minutes)\",\n    y = \"Count\"\n  )\n\np2 <- ggplot(study1, aes(x = outdoor_nonworkday)) +\n  geom_histogram(bins = 30) +\n  labs(\n    title = \"Non-Work/Non-School Days\",\n    x = \"Time spent outdoors (minutes)\",\n    y = \"Count\"\n  )\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](Stats431_Project-A_Task-B_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Summary of mean and standard deviation of the two variables\n\nstudy1 %>%\n  summarize(\n    workday_mean = mean(outdoor_workday),\n    workday_sd = sd(outdoor_workday),\n    nonworkday_mean = mean(outdoor_nonworkday),\n    nonworkday_sd = sd(outdoor_nonworkday)\n  ) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n| workday_mean| workday_sd| nonworkday_mean| nonworkday_sd|\n|------------:|----------:|---------------:|-------------:|\n|        117.5|      139.7|           151.1|         126.8|\n\n\n:::\n\n```{.r .cell-code}\nstudy1 <- study1 %>%\n  mutate(\n    outdoor_difference = outdoor_nonworkday - outdoor_workday\n  )\n\nstudy1 %>%\n  summarize(\n    mean_difference = mean(outdoor_difference),\n    sd_difference = sd(outdoor_difference)\n  ) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n| mean_difference| sd_difference|\n|---------------:|-------------:|\n|            33.6|         146.6|\n\n\n:::\n\n```{.r .cell-code}\n#T-Test for Confidence Interval\ntt_a <- study1 %$%\n  t.test(outdoor_difference, conf.level = 0.90)\n\ntidy(tt_a) %>%\n  select(estimate, conf.low, conf.high) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n| estimate| conf.low| conf.high|\n|--------:|--------:|---------:|\n|     33.6|     30.1|        37|\n\n\n:::\n:::\n\n\n## Conclusion\n\nMore people tend to spend less time outdoors when they have school or work. A lot of people spend as much as 2 hours outdoors when they're not working. On avereage, this comes close to 2.5 hours. The sample means tell us that the difference in time is about 34 minutes. Not many people spend more than 4 hours outside, regardless of whether they have work or school responsbilities. The t-test shows that the confidence interval in the means falls within 30.1 and 37 minute.\n\n# **Data Analysis B**\n\n## The Question\n\n**What does time spent outdoors between 9am and 5pm looks like on work or school days for female versus male participants?**\n\nThis can be done by comparing the means of the time spend by the two groups. And two plots woud better demonstrate how the time spent differs for the two groups.\n\n## Describing The Data \n\nThe variables we're looking at are outdoor_workday (time spent outdoors on work/ school days) for female and for male. We want to see if men spend more time outdoors than women do when they have school or work responsibilities.\n\n## Main Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Analysis B\n\n#Main Analysis: Histogram plots for time spent outdoors for the two groups.\n\n#Plots \nstudy1 %>%\n  ggplot(aes(x = outdoor_workday)) +\n  geom_histogram(bins = 30) +\n  facet_grid(gender ~ .) +\n  labs(\n    title = \"Outdoor Time on Work/School Days by Gender\",\n    x = \"Time spent outdoors (minutes)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Stats431_Project-A_Task-B_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Summary of the means and standard deviations\nstudy1 %>%\n  group_by(gender) %>%\n  summarize(\n    n = n(),\n    mean = mean(outdoor_workday),\n    sd = sd(outdoor_workday),\n    median = median(outdoor_workday),\n    min = min(outdoor_workday),\n    max = max(outdoor_workday)\n  ) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|gender |    n|  mean|    sd| median| min| max|\n|:------|----:|-----:|-----:|------:|---:|---:|\n|Male   | 2346| 162.2| 161.1|    120|   0| 480|\n|Female | 2475|  75.2|  98.8|     40|   0| 480|\n\n\n:::\n\n```{.r .cell-code}\n#T-Test for Confidence Interval\ntt_b <- t.test(\n  outdoor_workday ~ gender,\n  data = study1,\n  conf.level = 0.90\n)\n\ntt_b\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  outdoor_workday by gender\nt = 22.465, df = 3852.9, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n90 percent confidence interval:\n 80.64643 93.39227\nsample estimates:\n  mean in group Male mean in group Female \n           162.20844             75.18909 \n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(tt_b) %>%\n  select(estimate1, estimate2, estimate, conf.low, conf.high) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n| estimate1| estimate2| estimate| conf.low| conf.high|\n|---------:|---------:|--------:|--------:|---------:|\n|     162.2|      75.2|       87|     80.6|      93.4|\n\n\n:::\n:::\n\n\n## Conclusion\n\nConclusion: The results show that men typically spend more time outdoors than women do on work/school days. There's a considerable amount of men who spend up to 8 hours (around 480 minutes) outdoors. On average, men spend 162 minutes (estimate1) outdoors while women spend around 75 minutes (estimate2). The difference on time spent by the two groups is 87 minutes (estimate). The 90% confidence interval for the population mean is from 80.6 to 93.4 minutes.\n\n# **Data Analysis D**\n\n## The Question\n\n**How does regular sunscreen use differ between male and female adults ages 20 to 59?**\n\nThis can be done by comparing the regular sunscreen use between the two genders, using the variable regular_sunscreen in each category in gender.\n\n## Describing The Data \n\nThe variables we're looking at are regular_sunscreen (regular sunscreen use) between two gender groups (female vs male). Then, we look at the Risk difference to asnwer magnitude in the difference between the two groups. Then, Relative risk will tell us the ratio between the differnce, and Odss ratio result will tell us about the odds of regular use of sunscreen between the two groups.\n\n## Main Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Analysis D\n\n#Main Analysis: Stacked bar plots will show the difference in regular sunscreen use in female and male participants. The percentage of regular sunscreen use is calculated for the two groups.\n\nstudy1 %>%\n  tabyl(gender, regular_sunscreen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n gender Not Regular Regular\n   Male        2079     267\n Female        1758     717\n```\n\n\n:::\n\n```{.r .cell-code}\nstudy1 %>%\n  tabyl(gender, regular_sunscreen) %>%\n  adorn_percentages(\"row\") %>%\n  adorn_pct_formatting(digits = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n gender Not Regular Regular\n   Male       88.6%   11.4%\n Female       71.0%   29.0%\n```\n\n\n:::\n\n```{.r .cell-code}\n#Plot\nggplot(\n  study1,\n  aes(x = gender, fill = regular_sunscreen)\n) +\n  geom_bar(position = \"fill\") +\n  labs(\n    title = \"Regular Sunscreen Use by Gender\",\n    x = \"Gender\",\n    y = \"Proportion\",\n    fill = \"Sunscreen Use\"\n  )\n```\n\n::: {.cell-output-display}\n![](Stats431_Project-A_Task-B_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Calculations of Risk difference, Relative risk, and Odds ratio\n\n#Risk difference\nfemale_risk <- 717 / 2475\nmale_risk <- 267 / 2346\n\nrisk_difference <- female_risk - male_risk\n\nrisk_difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1758862\n```\n\n\n:::\n\n```{.r .cell-code}\n#Relative risk\nrelative_risk <- female_risk / male_risk\n\nrelative_risk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.545427\n```\n\n\n:::\n\n```{.r .cell-code}\n#Odds ratio\nfemale_odds <- 717 / 1758\nmale_odds <- 267 / 2079\n\nodds_ratio <- female_odds / male_odds\n\nodds_ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.17573\n```\n\n\n:::\n\n```{.r .cell-code}\ntibble(\n  Measure = c(\n    \"Risk Difference\",\n    \"Relative Risk\",\n    \"Odds Ratio\"\n  ),\n  Estimate = c(\n    risk_difference,\n    relative_risk,\n    odds_ratio\n  )\n) %>%\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Measure         | Estimate|\n|:---------------|--------:|\n|Risk Difference |     0.18|\n|Relative Risk   |     2.55|\n|Odds Ratio      |     3.18|\n\n\n:::\n:::\n\n\n## Conclusion\n\nThe results show that 29% of female and 11.4% of male participants reported having regular sunscreen use. The risk difference tells us that regular sunscreen use is 18% higer in women than it is is men. The relative risk tells us that the proportion of having regular sunscreen use is 2.55 higher for females than it is for males. The odds of using sunscreen regularly is 3.18 times for women.\n\n# **Data Analysis C**\n\n## The Question \n\n**How does the time spent outdoors on work/school days differ across education levels among adutls ages 20-59?**\n\nThis can be done by comparing outdoor_workday across the 4 education levels: less than highschool, high school or GED, some college or AA, and college graduate or above.\n\n## Describing The Data \n\nThe variables we're looking at are outdoor_workday (minutes spent outdoors from 9am to 5pm) and education. We compare the means in outdoor time across these groups. The linear model is then used to estiamte differences in the means of outdoor time, using less than high school as the reference group.\n\n## Main Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Analysis C\n\n#Main Analysis: Histograms are used to compare the outdoor time spent across 4 education level. Then, the linear model will calculate the 90% condifence interval for the difference in the mean of outdoor time across 4 groups.\n\nstudy1 %>%\n  ggplot(aes(x = outdoor_workday)) +\n  geom_histogram(bins = 30) +\n  facet_grid(\n    education ~ .,\n    labeller = label_wrap_gen(width = 25),\n    switch = \"y\"\n  ) +\n  labs(\n    title = \"Outdoor Time on Work/School Days by Education Level\",\n    x = \"Time spent outdoors (minutes)\",\n    y = \"Count\"\n  ) +\n  theme(\n    strip.placement = \"outside\",\n    strip.text.y.left = element_text(angle = 0)\n  )\n```\n\n::: {.cell-output-display}\n![](Stats431_Project-A_Task-B_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Summary of stats \nstudy1 %>%\n  group_by(education) %>%\n  summarize(\n    n = n(),\n    mean = mean(outdoor_workday),\n    sd = sd(outdoor_workday),\n    median = median(outdoor_workday),\n    min = min(outdoor_workday),\n    max = max(outdoor_workday)\n  ) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|education                 |    n|  mean|    sd| median| min| max|\n|:-------------------------|----:|-----:|-----:|------:|---:|---:|\n|Less than high school     |  738| 165.2| 171.9|    120|   0| 480|\n|High school or GED        | 1098| 149.2| 156.5|     90|   0| 480|\n|Some college or AA        | 1671| 116.5| 132.3|     60|   0| 480|\n|College graduate or above | 1314|  65.5|  86.8|     30|   0| 480|\n\n\n:::\n\n```{.r .cell-code}\n#Linear model comparing mean outdoor time across education levels\neducation_model <- lm(outdoor_workday ~ education, data = study1)\n\ntidy(education_model, conf.int = TRUE, conf.level = 0.90) %>%\n  select(term, estimate, conf.low, conf.high) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|term                               | estimate| conf.low| conf.high|\n|:----------------------------------|--------:|--------:|---------:|\n|(Intercept)                        |    165.2|    157.1|     173.4|\n|educationHigh school or GED        |    -16.0|    -26.6|      -5.4|\n|educationSome college or AA        |    -48.7|    -58.5|     -38.9|\n|educationCollege graduate or above |    -99.7|   -109.9|     -89.5|\n\n\n:::\n:::\n\n\n## Conclusion\n\nThe distribution is skewed to the right for all the groups. Those with high school degrees or less spend as much as 8 hours outdoors during work/school days. Mean time spent outdoors for participants with less than a high school degree is highest (162 minutes), while it is lowest for those with college degree or above (65 minutes). The linear model shows lower mean outdoor time for the other education groups compared with the group with less than a high school degree. Higher education levels are associated with lower time spent outdoors during work/school days.\n\n# Final Section\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxfun::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.6.2\n\nLocale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8\n\nPackage version:\n  askpass_1.2.1       backports_1.5.1     base64enc_0.1.6    \n  bit_4.6.0           bit64_4.8.6         blob_1.3.0         \n  broom_1.0.13        bslib_0.12.0        cachem_1.1.0       \n  callr_3.8.0         cellranger_1.1.0    cli_3.6.6          \n  clipr_0.8.1         compiler_4.6.1      conflicted_1.2.0   \n  cpp11_0.5.5         crayon_1.5.3        curl_8.0.0         \n  data.table_1.18.6.1 DBI_1.3.0           dbplyr_2.6.0       \n  digest_0.6.39       dplyr_1.2.1         dtplyr_1.3.3       \n  evaluate_1.0.5      farver_2.1.2        fastmap_1.2.0      \n  fontawesome_0.5.3   forcats_1.0.1       foreign_0.8-91     \n  fs_2.1.0            gargle_1.6.1        generics_0.1.4     \n  ggplot2_4.0.3       glue_1.8.1          googledrive_2.1.2  \n  googlesheets4_1.1.2 graphics_4.6.1      grDevices_4.6.1    \n  grid_4.6.1          gridExtra_2.3.1     gtable_0.3.6       \n  haven_2.5.5         highr_0.12          hms_1.1.4          \n  htmltools_0.5.9     htmlwidgets_1.6.4   httr_1.4.8         \n  ids_1.0.1           isoband_0.3.0       janitor_2.2.1      \n  jquerylib_0.1.4     jsonlite_2.0.0      knitr_1.52         \n  labeling_0.4.3      lifecycle_1.0.5     lubridate_1.9.5    \n  magrittr_2.0.5      memoise_2.0.1       methods_4.6.1      \n  mime_0.13           modelr_0.1.11       naniar_1.1.0       \n  nhanesA_1.4.1       norm_1.0.11.1       openssl_2.4.2      \n  otel_0.2.0          patchwork_1.3.2     pillar_1.11.1      \n  pkgconfig_2.0.3     plyr_1.8.9          prettyunits_1.2.0  \n  processx_3.9.0      progress_1.2.3      ps_1.9.3           \n  purrr_1.2.2         R6_2.6.1            ragg_1.5.2         \n  rappdirs_0.3.4      RColorBrewer_1.1-3  Rcpp_1.1.2         \n  readr_2.2.0         readxl_1.5.0        rematch_2.0.0      \n  rematch2_2.1.2      reprex_2.1.1        rlang_1.3.0        \n  rmarkdown_2.31      rstudioapi_0.19.0   rvest_1.0.5        \n  S7_0.2.2            sass_0.4.10         scales_1.4.0       \n  selectr_0.6.0       snakecase_0.11.1    stats_4.6.1        \n  stringi_1.8.9       stringr_1.6.0       sys_3.4.3          \n  systemfonts_1.3.2   textshaping_1.0.5   tibble_3.3.1       \n  tidyr_1.3.2         tidyselect_1.2.1    tidyverse_2.0.0    \n  timechange_0.4.0    tinytex_0.60        tools_4.6.1        \n  tzdb_0.5.0          UpSetR_1.4.1        utf8_1.2.6         \n  utils_4.6.1         uuid_1.2.2          vctrs_0.7.3        \n  viridis_0.6.5       viridisLite_0.4.3   visdat_0.6.1       \n  vroom_1.7.1         withr_3.0.3         xfun_0.61          \n  xml2_1.6.0          yaml_2.3.12        \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Stats431_Project-A_Task-B_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}